### ISSUE TITLE
Feature request: Switch to another testing framework

### ISSUE THREAD

**Issue by ThomasSchmidt** [episerver/Quicksilver#3]
It seems like the tests are using MsTest. I would guess this was used to make the visual studio experience better for EPiServer developers which are very likely to use visual studio, so they can easily run the tests directly from visual studio.

But consider using more modern testing frameworks like xUnit and NUnit. MsTest seems legacy at the moment and is bound to specific visual studio versions, especially considering that pretty much all Microsofts open source software, like the entire .net platform, roslyn and so on is using xUnit for example. Both xUnit and NUnit have visual studio runners so you can run the tests directly from visual studio.

This could be handled through a pull request.

**Comment by magnusstrale** [comment]
Hi,

Thank you for your input. We had a long internal discussion before deciding on which unit test framework to target. Your guess is spot-on, we assumed it would be the least developer friction in using MsTest since the vast majority of developers will be using Visual Studio.

Currently we're not planning to re-target our tests, but that may change in the future - especially if we get more input like this.
