### ISSUE TITLE
Change Admin Password

### ISSUE THREAD

**Issue by jon419** [episerver/Quicksilver#7]
I attempted to change the admin password in CMS->Admin.

When I logged out and logged back in, the password was still 'store'.

**Comment by quanmaiepi** [comment]
Hi,
We're aware of the issue. It should be fixed in upcoming release (if not in 1.2 version already)

**Comment by jon419** [comment]
So is the solution to eliminate the membership and role providers in the web.config?  How would one go about adding and removing CMS users when you are using the identity framework without some form of remote ldap or federated services?

**Comment by lunchin** [comment]
This is something that has to be fixed in admin mode and is on the backlog to be able to manage users from different authentication schemes.  You can use this blog post for a temporary solution until it is fixed in cms.

http://sveinaandahl.blogspot.no/2015/08/admin-tool-for-aspnet-identity.html

http://sveinaandahl.blogspot.no/2015/11/how-to-fix-roles-in-episerver-when.html

**Comment by quoctiennguyen** [comment]
Oh my god! basic security!

**Comment by quanmaiepi** [comment]
This should be completely fixed in latest version
